#!/bin/bash

docker build --build-arg  CUSTOM=$VAR -f $DOCKERFILE_PATH -t $IMAGE_NAME .
echo -e "$IMAGE_NAME,$VAR,Hello Tank XD,$DOCKERFILE_PATH"
docker build --build-arg  CUSTOM=$VAR -f $DOCKERFILE_PATH -t cbb107039/nptest:test .

